TranAnhDung_2122110043/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TranAnhDung_2122110043.Context;

namespace TranAnhDung_2122110043.Controllers
{
    public class BrandController : Controller
    {
        WebsiteAspEntities5 objWebsiteAspEntities4 = new WebsiteAspEntities5();
        // GET: Brand
        public ActionResult Index()
        {
            var listBrand = objWebsiteAspEntities4.Brands.ToList();
            return View(listBrand);
        }
        public ActionResult ProductBrand(int id)
        {
            var listProduct = objWebsiteAspEntities4.Products.Where(n => n.brand_id == id).ToList();
            return View(listProduct);
        }
    }
}

TranAnhDung_2122110043/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TranAnhDung_2122110043.Context;

namespace TranAnhDung_2122110043.Controllers
{
    public class CategoryController : Controller
    {
        WebsiteAspEntities5 objWebsiteAspEntities4 = new WebsiteAspEntities5();
        // GET: Category
        public ActionResult Index()
        {
            var listCategory = objWebsiteAspEntities4.Categories.ToList();
            return View(listCategory);
        }
        public ActionResult ProductCategory(int id)
        {
            var listProduct = objWebsiteAspEntities4.Products.Where(n => n.category_id==id).ToList();
        return View(listProduct); 
        }
    
    }
}

TranAnhDung_2122110043/Controllers/ProductController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TranAnhDung_2122110043.Context;
namespace TranAnhDung_2122110043.Controllers
{
    public class ProductController : Controller
    {
        WebsiteAspEntities5 db = new WebsiteAspEntities5();
        // GET: Product
        public ActionResult Index(string searchString, int? page)
        {
            var products = from p in db.Products
                           select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(p => p.name.Contains(searchString)
                                            || p.description.Contains(searchString)
                                            || p.Brand.name.Contains(searchString)
                                            || p.Category.name.Contains(searchString));
            }

            int pageSize = 12; // Change this to set how many products per page
            int pageNumber = (page ?? 1);

            return View(products.OrderBy(p => p.name).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Pagelistinglarge(string searchString, int? page)
        {
            var products = from p in db.Products
                           select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(p => p.name.Contains(searchString)
                                            || p.description.Contains(searchString)
                                            || p.Brand.name.Contains(searchString)
                                            || p.Category.name.Contains(searchString));
            }

            int pageSize = 8; // Change this to set how many products per page
            int pageNumber = (page ?? 1);

            return View(products.OrderBy(p => p.name).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Detail(int id)
        {
            using (WebsiteAspEntities5 objWebsiteAspEntities5 = new WebsiteAspEntities5())
            {
                var item = objWebsiteAspEntities5.Products.FirstOrDefault(p => p.id == id);
                if (item == null)
                {
                    return HttpNotFound();
                }

                // Get related products (same category, excluding the current product)
                var relatedProducts = objWebsiteAspEntities5.Products
                    .Where(p => p.category_id == item.category_id && p.id != id)
                    .Take(4)
                    .ToList();

                ViewBag.RelatedProducts = relatedProducts;

                return View(item);
            }
        }
    }
}

TranAnhDung_2122110043/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/Content/admin/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/Content/admin/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="~/Content/admin/dist/css/adminlte.min.css">
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <i class="far fa-user"></i> Quản lý
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <i class="fas fa-power-off"></i> Thoát
                    </a>
                </li>
            </ul>
        </nav>
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <a href="#" class="brand-link">
                <img src="~/Content/admin/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">Admin</span>
            </a>
            <div class="sidebar">
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/Content/admin/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Trần Anh Dũng</a>
                    </div>
                </div>
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <li class="nav-item">
                            <a href="" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Sản phẩm
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="@Url.Action("Index", "Product", new { area = "Admin" })" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Tất cả sản phẩm</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Index", "Category", new { area = "Admin" })" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Danh mục</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Index", "Brand", new { area = "Admin" })" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Thương hiệu</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Bài viết
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="post_index.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Tất cả bài viết</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="topic_index.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Chủ đề</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="order_index.html" class="nav-link">
                                <i class="fas fa-shopping-bag"></i>
                                <p>Đơn hàng</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="contact_index.html" class="nav-link">
                                <i class="fas fa-id-card"></i>
                                <p>Liên hệ</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Giao diện
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="menu_index.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Menu</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="banner_index.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Banner</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    Thành viên
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="user_index.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Tất cả thành viên</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="user_create.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Thêm thành viên</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-header">LABELS</li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-circle text-danger"></i>
                                <p class="text">Important</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-circle text-warning"></i>
                                <p>Warning</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-circle text-info"></i>
                                <p>Informational</p>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="content-wrapper">
            <!-- CONTENT -->
            <section class="content">
                
                        @RenderBody()
                        <hr />
                    
            </section>
            <!-- /.CONTENT -->
        </div>          
            <footer class="main-footer">
                <div class="float-right d-none d-sm-block">
                    <b>Version</b> 3.2.0
                </div>
                <strong>Sửa bởi: Trần Anh Dũng</strong> All rights reserved.
            </footer>
            <aside class="control-sidebar control-sidebar-dark">
            </aside>
        </div>
        <script src="~/Content/admin/plugins/jquery/jquery.min.js"></script>
        <script src="~/Content/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/Content/admin/dist/js/adminlte.min.js"></script>
</body>

</html>