TranAnhDung_2122110043/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TranAnhDung_2122110043.Context;
using TranAnhDung_2122110043.Models;

namespace TranAnhDung_2122110043.Controllers
{
    public class CartController : Controller
    {
        private readonly WebsiteAspEntities5 _context = new WebsiteAspEntities5();

        public ActionResult Index()
        {
            return View((List<CartModel>)Session["cart"] ?? new List<CartModel>());
        }

        [HttpPost]
        public ActionResult AddToCart(int id, int quantity)
        {
            try
            {
                if (Session["cart"] == null)
                {
                    List<CartModel> cart = new List<CartModel>();
                    cart.Add(new CartModel { Product = _context.Products.Find(id), Quantity = quantity });
                    Session["cart"] = cart;
                    Session["count"] = 1;
                }
                else
                {
                    List<CartModel> cart = (List<CartModel>)Session["cart"];
                    int index = IsExist(id);
                    if (index != -1)
                    {
                        cart[index].Quantity += quantity;
                    }
                    else
                    {
                        cart.Add(new CartModel { Product = _context.Products.Find(id), Quantity = quantity });
                        Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                    }
                    Session["cart"] = cart;
                }

                return Json(new { Success = true, Message = "Thêm giỏ hàng thành công!", CartCount = Session["count"] });
            }
            catch (Exception ex)
            {
                return Json(new { Success = false, Message = "Lỗi: " + ex.Message });
            }
        }

        [HttpPost]
        public ActionResult Remove(int id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.id == id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Success = true, Message = "Xóa sản phẩm thành công", CartCount = Session["count"] });
        }

        private int IsExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.id == id)
                    return i;
            return -1;
        }
    }
}

TranAnhDung_2122110043/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TranAnhDung_2122110043.Context;

namespace TranAnhDung_2122110043.Controllers
{
    public class CategoryController : Controller
    {
        WebsiteAspEntities5 objWebsiteAspEntities4 = new WebsiteAspEntities5();
        // GET: Category
        public ActionResult Index()
        {
            var listCategory = objWebsiteAspEntities4.Categories.ToList();
            return View(listCategory);
        }
        public ActionResult ProductCategory(int id)
        {
            var listProduct = objWebsiteAspEntities4.Products.Where(n => n.category_id==id).ToList();
        return View(listProduct); 
        }
    
    }
}

TranAnhDung_2122110043/Controllers/ProductController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TranAnhDung_2122110043.Context;
namespace TranAnhDung_2122110043.Controllers
{
    public class ProductController : Controller
    {
        WebsiteAspEntities5 db = new WebsiteAspEntities5();
        // GET: Product
        public ActionResult Index(string searchString, int? page)
        {
            var products = from p in db.Products
                           select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(p => p.name.Contains(searchString)
                                            || p.description.Contains(searchString)
                                            || p.Brand.name.Contains(searchString)
                                            || p.Category.name.Contains(searchString));
            }

            int pageSize = 12; // Change this to set how many products per page
            int pageNumber = (page ?? 1);

            return View(products.OrderBy(p => p.name).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Pagelistinglarge(string searchString, int? page)
        {
            var products = from p in db.Products
                           select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(p => p.name.Contains(searchString)
                                            || p.description.Contains(searchString)
                                            || p.Brand.name.Contains(searchString)
                                            || p.Category.name.Contains(searchString));
            }

            int pageSize = 8; // Change this to set how many products per page
            int pageNumber = (page ?? 1);

            return View(products.OrderBy(p => p.name).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Detail(int id)
        {
            using (WebsiteAspEntities5 objWebsiteAspEntities5 = new WebsiteAspEntities5())
            {
                var item = objWebsiteAspEntities5.Products.FirstOrDefault(p => p.id == id);
                if (item == null)
                {
                    return HttpNotFound();
                }

                // Get related products (same category, excluding the current product)
                var relatedProducts = objWebsiteAspEntities5.Products
                    .Where(p => p.category_id == item.category_id && p.id != id)
                    .Take(4)
                    .ToList();

                ViewBag.RelatedProducts = relatedProducts;

                return View(item);
            }
        }
    }
}

TranAnhDung_2122110043/Controllers/UserController.cs
using TranAnhDung_2122110043.Context;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TranAnhDung_2122110043.Context;

namespace DangThanhTu_2122110051.Controllers
{
    public class UserController : Controller
    {

        WebsiteAspEntities5 objAspNetWeb = new WebsiteAspEntities5();
        // GET: User

        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(User _user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var check = objAspNetWeb.Users.FirstOrDefault(s => s.email == _user.email);
                    if (check == null)
                    {
                        _user.password = GetMD5(_user.password);
                        objAspNetWeb.Configuration.ValidateOnSaveEnabled = false;
                        objAspNetWeb.Users.Add(_user);
                        objAspNetWeb.SaveChanges();
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ViewBag.error = "email already exists";
                        return View();
                    }
                }
                return View();
            }
            catch (Exception ex)
            {
                // Log the exception (ex) if necessary
                //ViewBag.error = "An error occurred during registration. Please try again later.";
                throw;
            }
        }


        //create a string MD5
        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }

   
            [HttpGet]
            public ActionResult Login()
            {
                return View();
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Login(string email, string password)
            {
                if (ModelState.IsValid)
                {


                    var f_password = GetMD5(password);
                    var data = objAspNetWeb.Users.Where(s => s.email.Equals(email) && s.password.Equals(f_password)).ToList();
                    if (data.Count() > 0)
                    {
                        //add session
                        Session["FullName"] = data.FirstOrDefault().firstname + " " + data.FirstOrDefault().lastname;
                        Session["Email"] = data.FirstOrDefault().email;
                        Session["idUser"] = data.FirstOrDefault().id;
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ViewBag.error = "Login failed";
                        return RedirectToAction("Login");
                    }
                }
                return View();
            }


            //Logout
            public ActionResult Logout()
            {
                Session.Clear();//remove session
                return RedirectToAction("Login");
            }



        }
    }

TranAnhDung_2122110043/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>WEB của Dũng</title>

    <link href="~/Content/images/favicon.ico" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="~/Scripts/js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="~/Scripts/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/~/Scripts/js/bootstrap.bundle.min.js"></script>
    <!-- Font awesome 5 -->
    <link href="~/Content/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="~/Content/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/responsive.css" rel="stylesheet" type="text/css" />
    <!-- custom javascript -->
    <script src="~/Scripts/js/script.js" type="text/javascript"></script>

</head>
<body>
    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-2 col-lg-3 col-md-12">
                        <a href="@Url.Action("Index", "Home")" class="brand-wrap">
                            <img class="logo" src="~/Content/images/logo.png">
                        </a> <!-- brand-wrap.// -->
                    </div>
                    <div class="col-xl-6 col-lg-5 col-md-6">
                        <form action="@Url.Action("Index", "Product")" method="get" class="form-inline my-2 my-lg-0">
                            <div class="input-group w-100">
                                <input class="form-control" type="search" placeholder="Tìm kiếm sản phẩm" aria-label="Search" name="searchString">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fa fa-search"></i> Tìm kiếm
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div><!-- col.// -->
                    <div class="col-xl-4 col-lg-4 col-md-6">
                        <div class="widgets-wrap float-md-right">
                            <div class="widget-header mr-3">
                                <a href="@(Session["FullName"] != null ? Url.Action("Index", "Home") : Url.Action("Login", "User"))" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-user"></i>
                                        <span class="notify">3</span>
                                    </div>
                                    <small class="text"> @(Session["FullName"] ?? "Đăng nhập") </small>
                                </a>
                            </div>
                        </div>

                        <div class="widget-header mr-3">
                            <a href="#" class="widget-view">
                                <div class="icon-area">
                                    <i class="fa fa-comment-dots"></i>
                                    <span class="notify">1</span>
                                </div>
                                <small class="text"> Message </small>
                            </a>
                        </div>
                        <div class="widget-header mr-3">
                            <a href="#" class="widget-view">
                                <div class="icon-area">
                                    <i class="fa fa-store"></i>
                                </div>
                                <small class="text"> Orders </small>
                            </a>
                        </div>
                        <div class="widget-header">
                            <a href="@Url.Action("Index", "Cart")" class="widget-view">
                                <div class="icon-area">
                                    <i class="fa fa-shopping-cart"></i>
                                    <span class="notify" id="CartCount">@(Session["count"] ?? 0)</span>
                                </div>
                                <small class="text">Giỏ hàng</small>
                            </a>
                        </div>
                    </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->


        <nav class="navbar navbar-main navbar-expand-lg border-bottom">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"> <i class="fa fa-bars text-muted mr-2"></i> Danh mục </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Máy móc</a>
                                <a class="dropdown-item" href="#">Đồ điện tử</a>
                                <a class="dropdown-item" href="#">Đồ gia dụng</a>
                                <a class="dropdown-item" href="#">Đồ gia dụng và nhà bếp</a>
                                <a class="dropdown-item" href="#">Dịch vụ và thiết bị</a>
                                <a class="dropdown-item" href="#">Các mặt hàng chăm sóc sức khỏe</a>
                                <a class="dropdown-item" href="#">Đồ chơi và sở thích</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Sẵn sàng để giao hàng</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Triển lãm thương mại</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Dịch vụ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Bán với chúng tôi</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Trang demo</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="page-index.html">Chính</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Category")">Tất cả danh mục</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Product")">Danh sách sản phẩm</a>
                                <a class="dropdown-item" href="@Url.Action("Pagelistinglarge", "Product")">Lưới danh sách</a>
                                <a class="dropdown-item" href="@Url.Action("Index", " Cart")">Giỏ hàng</a>
                                <a class="dropdown-item" href="page-detail-product.html">Mục chi tiết</a>
                                <a class="dropdown-item" href="page-content.html">Nội dung thông tin</a>
                                <a class="dropdown-item" href="@Url.Action("Login", "User")">Đăng nhập trang</a>
                                <a class="dropdown-item" href="@Url.Action("Register", "User")">Đăng ký trang</a>
                                <a class="dropdown-item disabled text-muted" href="#">Nhiều thành phần hơn</a>
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-md-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Get the app</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" data-toggle="dropdown">English</a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#">Russian</a>
                                <a class="dropdown-item" href="#">French</a>
                                <a class="dropdown-item" href="#">Spanish</a>
                                <a class="dropdown-item" href="#">Chinese</a>
                            </div>
                        </li>
                    </ul>
                </div> <!-- collapse .// -->
            </div> <!-- container .// -->
        </nav>
    </header>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <!-- ========================= FOOTER ========================= -->
    <footer class="section-footer bg-secondary">
        <div class="container">
            <section class="footer-top padding-y-lg text-white">
                <div class="row">
                    <aside class="col-md col-6">
                        <h6 class="title">Thương hiệu</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Adidas</a></li>
                            <li> <a href="#">Puma</a></li>
                            <li> <a href="#">Reebok</a></li>
                            <li> <a href="#">Nike</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Công ty</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Về chúng tôi</a></li>
                            <li> <a href="#">Sự nghiệp</a></li>
                            <li> <a href="#">Tìm cửa hàng</a></li>
                            <li> <a href="#">Quy tắc và điều khoản</a></li>
                            <li> <a href="#">Sơ đồ trang web</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Trợ giúp</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Liên hệ với chúng tôi</a></li>
                            <li> <a href="#">Hoàn tiền</a></li>
                            <li> <a href="#">Trạng thái đơn hàng</a></li>
                            <li> <a href="#">Thông tin giao hàng</a></li>
                            <li> <a href="#">Mở tranh chấp</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Tài khoản</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#"> Đăng nhập người dùng </a></li>
                            <li> <a href="#"> Đăng ký người dùng </a></li>
                            <li> <a href="#"> Thiết lập tài khoản </a></li>
                            <li> <a href="#"> Đơn hàng của tôi </a></li>
                        </ul>
                    </aside>
                    <aside class="col-md">
                        <h6 class="title">Mạng xã hội</h6>
                        <ul class="list-unstyled">
                            <li><a href="#"> <i class="fab fa-facebook"></i> Facebook </a></li>
                            <li><a href="#"> <i class="fab fa-twitter"></i> Twitter </a></li>
                            <li><a href="#"> <i class="fab fa-instagram"></i> Instagram </a></li>
                            <li><a href="#"> <i class="fab fa-youtube"></i> Youtube </a></li>
                        </ul>
                    </aside>
                </div><!-- row.// -->
            </section>	<!-- footer-top.// -->

            <section class="footer-bottom text-center">

                <p class="text-white">Privacy Policy - Terms of Use - User Information Legal Enquiry Guide</p>
                <p class="text-muted"> &copy 2019 Company name, All rights reserved </p>
                <br>
            </section>
        </div><!-- //container -->
    </footer>
    <!-- ========================= FOOTER END // ========================= -->

</body>
</html>